### ISSUE TITLE
Post data not being submitted to Buildkite

### ISSUE THREAD

**Issue by swebb** [buildkite/test-collector-javascript#36]
Several customers have encountered an error where their data is not being submitted to Buildkite. When run with debug logging enabled we can see the `Post` message [here](https://github.com/buildkite/test-collector-javascript/blob/6abcf44df181d8fe377be481f0fdc894306f547d/jest/reporter.js#L55); however, no response or error messages are logged. It's currently not clear what the problem is.

One possibility is that customers have stubbed the `axios` methods so the Post never occurs. However, it's not clear if this is really the issue.

**Comment by swebb** [comment]
I've reviewed our logs and I can't find any requests that correspond to the missing data. So it appears as though it's not reaching Buildkite servers.

We have seen this issue on builds using both Linux and MacOS. On arm64 and amd64 systems. One customer is able to submit tests using Microsoft Windows, but not using MacOS.

The behaviour is very strange to me. The [code to post](https://github.com/buildkite/test-collector-javascript/blob/6abcf44df181d8fe377be481f0fdc894306f547d/jest/reporter.js#L55) logs on both success and failure there should be something, but nothing appears. This adds weight to the idea that the method has been stubbed/mocked. However, we've also got a customer that has run their test suite on both Microsoft Windows and MacOS. It send data correctly under Microsoft Windows, but not for MacOS.

**Comment by swebb** [comment]
@mariovisic have you got any suggestions about what might be the problem or what steps we should take for troubleshooting?

**Comment by mariovisic** [comment]
Seems like a tricky one @swebb 

If you're able to find an open source test suite that has the behavour, it would really help track down the issue, as you could peel back the layers to figure out where the failure is.

axios being stubbed or http being monkey patched could definitely be the issue, another thing to investigate is that jest may be exiting before it can complete the http request. I do see a warning that's displayed that mentions that the reporter is still running when jest wants to exit. In jasmine you can have the reporter notify when it's complete by running the jasmine supplied `done` function, I wonder if there's anything in jest we can do to ensure that the reporter plays nice by the framework.

I saw this `forceExit` flag which may cause the test suite to exit before the reporter can complete: https://jestjs.io/docs/next/cli#--forceexit

**Comment by gchan** [comment]
Hi @mariovisic. 

> jest may be exiting before it can complete the http request. 

My understanding is that axios is promised-based and the HTTP request is async. Is there a way to make an sync request via axois? Or can we swap it out for a different library which supports sync HTTP requests?

I've seen a private build that seemed to have this error print this out in the logs:

> Force exiting Jest: Have you considered using `--detectOpenHandles` to detect async operations that kept running after all tests finished?

**Comment by mariovisic** [comment]
I think all http libraries will either use callbacks or promises, you can emulate a sync http request using `async/await` with axios and marking the `onTestResult` method as `async` that might help, but would need jest to play ball.

**Comment by mariovisic** [comment]
Oh, I might be wrong, you could also experiment with this: https://www.npmjs.com/package/sync-request

**Comment by swebb** [comment]
Thanks @mariovisic. That's some great ideas to try out.

**Comment by gchan** [comment]
We believe the root cause is due to the --forceExit option being used in Jest.

--forceExit is not recommended for daily use. We could document that somewhere (README and/or docs).

"This feature is an escape-hatch. If Jest doesn't exit at the end of a test run, it means external resources are still being held on to or timers are still pending in your code. It is advised to tear down external resources after each test to make sure Jest can shut down cleanly. You can use --detectOpenHandles to help track it down."

https://jestjs.io/docs/cli#--forceexit

The other thing @swebb  mentioned was that we could possible detect when --forceExit option is set to true and print out a warning to the console letting them know this could result in missing Test Executions in Buildkite. I tracked down potentially relevant code here https://github.com/facebook/jest/blob/a20bd2c31e126fc998c2407cfc6c1ecf39ead709/packages/jest-cli/src/cli/index.ts#L124

So two potential tasks:

2. Document that --forceExit is not recommended for daily use and could result in missing Test Executions
3. Update collector code to detect forceExit and print a warning to the console

**Comment by gchan** [comment]
Documentation about this issue
https://buildkite.com/docs/test-analytics/javascript-collectors#troubleshooting-missing-test-executions-and-forceexit

https://github.com/buildkite/test-collector-javascript/pull/39 adds a warning whenever `--forceExit` is used with Jest
